// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ColorMode: typeof import('./src/components/ColorMode.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconFaBrandsGithub: typeof import('~icons/fa-brands/github')['default']
    IconFaSolidMoon: typeof import('~icons/fa-solid/moon')['default']
    IconFaSolidSun: typeof import('~icons/fa-solid/sun')['default']
    Login: typeof import('./src/components/auth/Login.vue')['default']
    Navbar: typeof import('./src/components/navigation/Navbar.vue')['default']
  }
}

export { }
